### PR TITLE
Added favicon. Solves issue #20 and #21

### PR DESCRIPTION
**Pull request by aakashkhatter1296**
The favicon added is : 
afullstop-icon

Preview at https://aakashkhatter1296.github.io/afullstop/pages/gradientBackground.html

### CODE REVIEW

**Comment by choyiny** [comment]
You can link issues by typing: #20 #21 

Can you possibly include your favicon into all the pages? It looks very nice. @Vailfire you could investigate in including this to your js branch.

**Comment by aakashkhatter1296** [comment]
@choyiny Thanks. Sure, I'll include it in all the pages.

**Comment by choyiny** [comment]
Thanks, merged.

**Comment by calvinrbnspiess** [comment]
Picked the favicon into the `js`-branch and added it to the webpack routine. 2ef05248611f330dfc057034d828e9086c426dae

**Pull request merged**
