### PR TITLE
Custom Page - rainbow 

### PR DESCRIPTION
**Pull request by cedricium**
# rainbow
#### a colorful and friendly custom page for the "this is a full stop, not a period" website.

This is my first attempt at creating a custom page. All code can be found in the `afullstop.html` document, where you will find the HTML and internal CSS for the page. For a live preview of the page, visit [cedricamaya.me/afullstop](http://cedricamaya.me/afullstop/). 

Architect's Daughter font found on Google Fonts.

### CODE REVIEW

**Comment by choyiny** [comment]
I will merge this, but as a challenge for yourself, you can expand this page from a motionless one to a more interesting one by using javascript libraries.

These are some libraries that I find amazing:
https://github.com/wagerfield/parallax/
http://bouncejs.com/
https://github.com/shedali/jGravity

Check them out! Also, add your name to `README.MD`. Thanks for contributing!

**Comment by cedricium** [comment]
Thank you so much! I'm currently only familiar with HTML and CSS but have been wanting to learn JavaScript - this will be an awesome project to work on.

**Comment by cedricium** [comment]
Update to README.md done with PR #22

**Comment by cedricium** [comment]
The content section now slides into the page, giving the page a little animation. Hope this works for you. 

The live version can be found here: [cedricamaya.me/afullstop](http://cedricamaya.me/afullstop/).

**Comment by choyiny** [comment]
Hope you learned something about javascript. Merged!

**Pull request merged**
