### PR TITLE
Make text configurable

### PR DESCRIPTION
**Pull request by faustbrian**
Solves https://github.com/choyiny/afullstop/issues/7

### CODE REVIEW

**Comment by choyiny** [comment]
Can you create a new html file under /pages/? name it configurable.html

Also, adding some more documentation and comments would be great.

**Comment by faustbrian** [comment]
Sure, will update it and move it later.

**Comment by choyiny** [comment]
Before I merge, can you add yourself to the Contributors list in README.MD? Thanks for contributing to this project!

**Comment by choyiny** [comment]
Merge conflict! Something might've changed after you forked!

**Pull request closed without merging**
