### PR TITLE
Added changing gradient background

### PR DESCRIPTION
**Pull request by aakashkhatter1296**
Preview on https://aakashkhatter1296.github.io/afullstop/pages/gradientBackground.html

### CODE REVIEW

**Comment by choyiny** [comment]
#1 
This is a very nice page, I would definitely want to change this to the main page. However, can you remove the extremely bright colors as it does hurt the eyes a bit. (especially if you have a bright screen)

**Comment by aakashkhatter1296** [comment]
@choyiny thanks. I'll change the color scheme to less bright colors and submit a PR.

**Comment by aakashkhatter1296** [comment]
@choyiny I have updated the color scheme to less brighter colors. Please take a look.

**Comment by choyiny** [comment]
Merged, thanks!

**Comment by aakashkhatter1296** [comment]
@choyiny should I add the gradient background to the main page ?

**Comment by choyiny** [comment]
Yep, that'd be great!

**Pull request merged**
