### PR TITLE
added metadata

### PR DESCRIPTION
**Pull request by supermansi**
Added keywords and elaborated the description in the `meta` tags.

### CODE REVIEW

**Comment by choyiny** [comment]
can you add it to all the pages?

**Comment by supermansi** [comment]
Sure thing.

**Comment by choyiny** [comment]
forgot to ask you to put your name in `README.MD` under Contributors. Will merge after you've done that.

**Comment by supermansi** [comment]
Ah, will do that.

**Comment by choyiny** [comment]
Merged.

**Pull request merged**
