### PR TITLE
Added Typed.js Animation

### PR DESCRIPTION
**Pull request by DaylightFox**
Probably not the most efficient implementation but oh well

### CODE REVIEW

**Comment by choyiny** [comment]
Seems awesome, but can you make a preview with Github pages? Currently http://magicp.github.io/afullstop is inaccessible.

Also can you minify typed.js?

#1

**Comment by DaylightFox** [comment]
Oh right, sorry
Should be up now although I think there's now an issue with the name showing up.

**Comment by choyiny** [comment]
Is there something you could do to differentiate your version with the main page? For example, make it a terminal styled page.

**Comment by DaylightFox** [comment]
Okay, all sorted now. Page has been given a terminal like feel and some interactivity.
https://magicp.github.io/afullstop/pages/typedText.html

Sorry for all the commits - I'm still fairly new to Git.

**Comment by choyiny** [comment]
Before I merge this can you also add your name to README.md contributors?

**Comment by DaylightFox** [comment]
Done

**Comment by choyiny** [comment]
Merged. Thanks!

**Pull request merged**
