### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by andy-j**
Style & indentation consistency changes.

### CODE REVIEW

**Comment by choyiny** [comment]
Thanks, looks good! Can you possibly publish your site to Github Pages so I can preview it before merging? Thanks!

#1

**Comment by andy-j** [comment]
Absolutely!

https://andy-j.github.io/afullstop/

Andy

**Comment by choyiny** [comment]
It would be great if you could introduce new UI changes to the webpage. Also, can you create a new html file for your page? I'm getting merge conflicts.

**Comment by andy-j** [comment]
Merge conflicts should just be spacing & indentation - I added in the animate.css reference and all of the text is the same.

**Comment by choyiny** [comment]
There are still merge conflicts, can you create a new page under `/pages/` ?

**Comment by choyiny** [comment]
Do you still intend to work on this PR? @andy-j

**Comment by choyiny** [comment]
Closed.

**Pull request closed without merging**
